namespace PdfLexer.DOM;

public enum PageLabelStyle
{
    None,
    Decimal, // 1, 2, 3...
    UpperRoman, // I, II, III...
    LowerRoman, // i, ii, iii...
    UpperAlpha, // A, B, C...
    LowerAlpha // a, b, c...
}

public record struct PageLabel(PageLabelStyle Style = PageLabelStyle.Decimal, string? Prefix = null, int Start = 1);
