namespace PdfLexer.DOM;

public enum PageSize
{
    A0x4,
    A0x2,
    A0,
    A1,
    A2,
    A3,
    A4,
    A5,
    A6,
    A7,
    A8,
    A9,
    A10,
    B0,
    B1,
    B2,
    B3,
    B4,
    B5,
    B6,
    B7,
    B8,
    B9,
    B10,
    C0,
    C1,
    C2,
    C3,
    C4,
    C5,
    C6,
    C7,
    C8,
    C9,
    C10,
    RA0,
    RA1,
    RA2,
    RA3,
    RA4,
    SRA0,
    SRA1,
    SRA2,
    SRA3,
    SRA4,
    EXECUTIVE,
    FOLIO,
    LEGAL,
    LETTER,
    TABLOID,
}

internal static class PageSizeHelpers
{
    internal static PdfArray GetMediaBox(PageSize size)
    {
        if (!PageSizeLookup.TryGetValue(size, out var array))
        {
            throw new PdfLexerException("Unknown media box for page size: " + size.ToString());
        }
        return array.CloneShallow();
    }
    internal static Dictionary<PageSize, PdfArray> PageSizeLookup = new Dictionary<PageSize, PdfArray>
    {
        [PageSize.A0x4] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 4767.87m, 6740.79m },
        [PageSize.A0x2] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 3370.39m, 4767.87m },
        [PageSize.A0] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 2383.94m, 3370.39m },
        [PageSize.A1] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 1683.78m, 2383.94m },
        [PageSize.A2] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 1190.55m, 1683.78m },
        [PageSize.A3] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 841.89m, 1190.55m },
        [PageSize.A4] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 595.28m, 841.89m },
        [PageSize.A5] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 419.53m, 595.28m },
        [PageSize.A6] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 297.64m, 419.53m },
        [PageSize.A7] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 209.76m, 297.64m },
        [PageSize.A8] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 147.4m, 209.76m },
        [PageSize.A9] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 104.88m, 147.4m },
        [PageSize.A10] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 73.7m, 104.88m },
        [PageSize.B0] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 2834.65m, 4008.19m },
        [PageSize.B1] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 2004.09m, 2834.65m },
        [PageSize.B2] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 1417.32m, 2004.09m },
        [PageSize.B3] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 1000.63m, 1417.32m },
        [PageSize.B4] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 708.66m, 1000.63m },
        [PageSize.B5] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 498.9m, 708.66m },
        [PageSize.B6] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 354.33m, 498.9m },
        [PageSize.B7] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 249.45m, 354.33m },
        [PageSize.B8] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 175.75m, 249.45m },
        [PageSize.B9] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 124.72m, 175.75m },
        [PageSize.B10] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 87.87m, 124.72m },
        [PageSize.C0] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 2599.37m, 3676.54m },
        [PageSize.C1] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 1836.85m, 2599.37m },
        [PageSize.C2] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 1298.27m, 1836.85m },
        [PageSize.C3] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 918.43m, 1298.27m },
        [PageSize.C4] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 649.13m, 918.43m },
        [PageSize.C5] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 459.21m, 649.13m },
        [PageSize.C6] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 323.15m, 459.21m },
        [PageSize.C7] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 229.61m, 323.15m },
        [PageSize.C8] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 161.57m, 229.61m },
        [PageSize.C9] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 113.39m, 161.57m },
        [PageSize.C10] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 79.37m, 113.39m },
        [PageSize.RA0] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 2437.8m, 3458.27m },
        [PageSize.RA1] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 1729.13m, 2437.8m },
        [PageSize.RA2] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 1218.9m, 1729.13m },
        [PageSize.RA3] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 864.57m, 1218.9m },
        [PageSize.RA4] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 609.45m, 864.57m },
        [PageSize.SRA0] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 2551.18m, 3628.35m },
        [PageSize.SRA1] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 1814.17m, 2551.18m },
        [PageSize.SRA2] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 1275.59m, 1814.17m },
        [PageSize.SRA3] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 907.09m, 1275.59m },
        [PageSize.SRA4] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 637.8m, 907.09m },
        [PageSize.EXECUTIVE] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 521.86m, 756.0m },
        [PageSize.FOLIO] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 612.0m, 936.0m },
        [PageSize.LEGAL] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 612.0m, 1008.0m },
        [PageSize.LETTER] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 612.0m, 792.0m },
        [PageSize.TABLOID] = new PdfArray { PdfCommonNumbers.Zero, PdfCommonNumbers.Zero, 792.0m, 1224.0m }
    };
}