// AUTOGENERATED DO NOT MODIFY

using PdfLexer;
using static PdfLexer.Validation.MathUtil;

namespace PdfLexer.Validation;

internal partial class APM_ArrayOfXFA : ISpecification<PdfArray>
{
    public static string Name { get; } = "ArrayOfXFA";
    public static bool RuleGroup() { return true; }
    public static bool AppliesTo(decimal version, List<string> extensions) => true; // managed by links
    public static void Validate(PdfValidator ctx, CallStack stack, PdfArray obj, IPdfObject? parent)
    {
        ctx.Run<APM_ArrayOfXFA_0x, PdfArray>(stack, obj, parent);
        ctx.Run<APM_ArrayOfXFA_1x, PdfArray>(stack, obj, parent);

    }

    public static bool MatchesType(PdfValidator ctx, PdfArray obj) 
    {
        return false;
    }
}

/// <summary>
/// ArrayOfXFA_0* Table 224 and Clause 12.7.8 in ISO 32000-1:2008
/// </summary>
internal partial class APM_ArrayOfXFA_0x : ISpecification<PdfArray>
{
    public static string Name { get; } = "ArrayOfXFA_0*";
    public static bool RuleGroup() { return false; }
    public static bool MatchesType(PdfValidator ctx, PdfArray obj) { return false; } // not used for children
    public static bool AppliesTo(decimal version, List<string> extensions) { return version >= 1.6m && version < 2.0m; }
    public static void Validate(PdfValidator ctx, CallStack stack, PdfArray obj, IPdfObject? parent)
    {
        for (var i = 0; i<obj.Count; i+=2) 
        {
            CheckSingle(i);
        }
        void CheckSingle(int n) 
        {
            var val = ctx.GetRequired<PdfString, APM_ArrayOfXFA_0x>(obj, n, IndirectRequirement.Either);
            if (val == null) { return; }
            // no special cases
            // no value restrictions
            // no linked objects
            
        }
    }
}

/// <summary>
/// ArrayOfXFA_1* 
/// </summary>
internal partial class APM_ArrayOfXFA_1x : ISpecification<PdfArray>
{
    public static string Name { get; } = "ArrayOfXFA_1*";
    public static bool RuleGroup() { return false; }
    public static bool MatchesType(PdfValidator ctx, PdfArray obj) { return false; } // not used for children
    public static bool AppliesTo(decimal version, List<string> extensions) { return version >= 1.6m && version < 2.0m; }
    public static void Validate(PdfValidator ctx, CallStack stack, PdfArray obj, IPdfObject? parent)
    {
        for (var i = 1; i<obj.Count; i+=2) 
        {
            CheckSingle(i);
        }
        void CheckSingle(int n) 
        {
            var val = ctx.GetRequired<PdfStream, APM_ArrayOfXFA_1x>(obj, n, IndirectRequirement.MustBeIndirect);
            if (val == null) { return; }
            // no special cases
            // no value restrictions
            ctx.Run<APM_Stream, PdfDictionary>(stack, val.Dictionary, obj);
            
        }
    }
}

