// AUTOGENERATED DO NOT MODIFY

using PdfLexer;
using static PdfLexer.Validation.MathUtil;

namespace PdfLexer.Validation;

internal partial class APM_ArrayOfArraysXPTSValues : ISpecification<PdfArray>
{
    public static string Name { get; } = "ArrayOfArraysXPTSValues";
    public static bool RuleGroup() { return true; }
    public static bool AppliesTo(decimal version, List<string> extensions) => true; // managed by links
    public static void Validate(PdfValidator ctx, CallStack stack, PdfArray obj, IPdfObject? parent)
    {
        ctx.Run<APM_ArrayOfArraysXPTSValues_x, PdfArray>(stack, obj, parent);

    }

    public static bool MatchesType(PdfValidator ctx, PdfArray obj) 
    {
        return false;
    }
}

/// <summary>
/// ArrayOfArraysXPTSValues_* Table 272, XPTS cell
/// </summary>
internal partial class APM_ArrayOfArraysXPTSValues_x : ISpecification<PdfArray>
{
    public static string Name { get; } = "ArrayOfArraysXPTSValues_*";
    public static bool RuleGroup() { return false; }
    public static bool MatchesType(PdfValidator ctx, PdfArray obj) { return false; } // not used for children
    public static bool AppliesTo(decimal version, List<string> extensions) { return false; }
    public static void Validate(PdfValidator ctx, CallStack stack, PdfArray obj, IPdfObject? parent)
    {
        for (var i = 0; i<obj.Count; i+=1) 
        {
            CheckSingle(i);
        }
        void CheckSingle(int n) 
        {
            var (val, wasIR) = ctx.GetOptional<PdfArray, APM_ArrayOfArraysXPTSValues_x>(obj, n, IndirectRequirement.Either);
            if (val == null) { return; }
            var parentNames = parent?.Get("Names");
            if (!(eq(((val as PdfArray)?.Count),((parentNames as PdfArray)?.Count)))) 
            {
                ctx.Fail<APM_ArrayOfArraysXPTSValues_x>($"Value failed special case check: fn:Eval(fn:ArrayLength(*)==fn:ArrayLength(parent::Names))");
            }
            // no value restrictions
            ctx.Run<APM_ArrayOfXPTSValues, PdfArray>(stack, val, obj);
            
        }
    }
}

