// AUTOGENERATED DO NOT MODIFY

using PdfLexer;
using static PdfLexer.Validation.MathUtil;

namespace PdfLexer.Validation;

using System.Linq;

internal partial class APM_CalRGBDict : APM_CalRGBDict__Base
{
}

internal partial class APM_CalRGBDict__Base : ISpecification<PdfDictionary>
{
    public static bool RuleGroup() { return true; }
    public static string Name { get; } = "CalRGBDict";
    public static bool AppliesTo(decimal version, List<string> extensions) => true; // managed by links
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        ctx.Run<APM_CalRGBDict_WhitePoint, PdfDictionary>(stack, obj, parent);
        ctx.Run<APM_CalRGBDict_BlackPoint, PdfDictionary>(stack, obj, parent);
        ctx.Run<APM_CalRGBDict_Gamma, PdfDictionary>(stack, obj, parent);
        ctx.Run<APM_CalRGBDict_Matrix, PdfDictionary>(stack, obj, parent);
        switch (ctx.Version) {
            case 1.1m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_11.Contains(x)))
                {
                    ctx.Fail<APM_CalRGBDict>($"Unknown field {extra} for version 1.1");
                }
                break;
            case 1.2m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_12.Contains(x)))
                {
                    ctx.Fail<APM_CalRGBDict>($"Unknown field {extra} for version 1.2");
                }
                break;
            case 1.3m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_13.Contains(x)))
                {
                    ctx.Fail<APM_CalRGBDict>($"Unknown field {extra} for version 1.3");
                }
                break;
            case 1.4m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_14.Contains(x)))
                {
                    ctx.Fail<APM_CalRGBDict>($"Unknown field {extra} for version 1.4");
                }
                break;
            case 1.5m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_15.Contains(x)))
                {
                    ctx.Fail<APM_CalRGBDict>($"Unknown field {extra} for version 1.5");
                }
                break;
            case 1.6m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_16.Contains(x)))
                {
                    ctx.Fail<APM_CalRGBDict>($"Unknown field {extra} for version 1.6");
                }
                break;
            case 1.7m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_17.Contains(x)))
                {
                    ctx.Fail<APM_CalRGBDict>($"Unknown field {extra} for version 1.7");
                }
                break;
            case 1.8m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_18.Contains(x)))
                {
                    ctx.Fail<APM_CalRGBDict>($"Unknown field {extra} for version 1.8");
                }
                break;
            case 1.9m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_19.Contains(x)))
                {
                    ctx.Fail<APM_CalRGBDict>($"Unknown field {extra} for version 1.9");
                }
                break;
            case 2.0m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_20.Contains(x)))
                {
                    ctx.Fail<APM_CalRGBDict>($"Unknown field {extra} for version 2.0");
                }
                break;
            default:
                break;
        }
    }

    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) 
    {
        return false;
    }

    public static List<string> AllowedFields_11 { get; } = new List<string> 
    {
        "WhitePoint", "BlackPoint", "Gamma", "Matrix"
    };
    public static List<string> AllowedFields_12 { get; } = new List<string> 
    {
        "WhitePoint", "BlackPoint", "Gamma", "Matrix"
    };
    public static List<string> AllowedFields_13 { get; } = new List<string> 
    {
        "WhitePoint", "BlackPoint", "Gamma", "Matrix"
    };
    public static List<string> AllowedFields_14 { get; } = new List<string> 
    {
        "WhitePoint", "BlackPoint", "Gamma", "Matrix"
    };
    public static List<string> AllowedFields_15 { get; } = new List<string> 
    {
        "WhitePoint", "BlackPoint", "Gamma", "Matrix"
    };
    public static List<string> AllowedFields_16 { get; } = new List<string> 
    {
        "WhitePoint", "BlackPoint", "Gamma", "Matrix"
    };
    public static List<string> AllowedFields_17 { get; } = new List<string> 
    {
        "WhitePoint", "BlackPoint", "Gamma", "Matrix"
    };
    public static List<string> AllowedFields_18 { get; } = new List<string> 
    {
        "WhitePoint", "BlackPoint", "Gamma", "Matrix"
    };
    public static List<string> AllowedFields_19 { get; } = new List<string> 
    {
        "WhitePoint", "BlackPoint", "Gamma", "Matrix"
    };
    public static List<string> AllowedFields_20 { get; } = new List<string> 
    {
        "WhitePoint", "BlackPoint", "Gamma", "Matrix"
    };
    


}

/// <summary>
/// CalRGBDict_WhitePoint Table 63
/// </summary>
internal partial class APM_CalRGBDict_WhitePoint : APM_CalRGBDict_WhitePoint__Base
{
}


internal partial class APM_CalRGBDict_WhitePoint__Base : ISpecification<PdfDictionary>
{
    public static string Name { get; } = "CalRGBDict_WhitePoint";
    public static bool RuleGroup() { return false; }
    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) { return false; } // not used for children
    public static bool AppliesTo(decimal version, List<string> extensions) { return version >= 1.1m; }
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        var val = ctx.GetRequired<PdfArray, APM_CalRGBDict_WhitePoint>(obj, "WhitePoint", IndirectRequirement.Either);
        if (val == null) { return; }
        // no special cases
        // no value restrictions
        ctx.Run<APM_WhitepointArray, PdfArray>(stack, val, obj);
        
    }


}

/// <summary>
/// CalRGBDict_BlackPoint 
/// </summary>
internal partial class APM_CalRGBDict_BlackPoint : APM_CalRGBDict_BlackPoint__Base
{
}


internal partial class APM_CalRGBDict_BlackPoint__Base : ISpecification<PdfDictionary>
{
    public static string Name { get; } = "CalRGBDict_BlackPoint";
    public static bool RuleGroup() { return false; }
    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) { return false; } // not used for children
    public static bool AppliesTo(decimal version, List<string> extensions) { return version >= 1.1m; }
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        var val = ctx.GetOptional<PdfArray, APM_CalRGBDict_BlackPoint>(obj, "BlackPoint", IndirectRequirement.Either);
        if (val == null) { return; }
        // no special cases
        // no value restrictions
        ctx.Run<APM_BlackpointArray, PdfArray>(stack, val, obj);
        
    }


}

/// <summary>
/// CalRGBDict_Gamma 
/// </summary>
internal partial class APM_CalRGBDict_Gamma : APM_CalRGBDict_Gamma__Base
{
}


internal partial class APM_CalRGBDict_Gamma__Base : ISpecification<PdfDictionary>
{
    public static string Name { get; } = "CalRGBDict_Gamma";
    public static bool RuleGroup() { return false; }
    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) { return false; } // not used for children
    public static bool AppliesTo(decimal version, List<string> extensions) { return version >= 1.1m; }
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        var val = ctx.GetOptional<PdfArray, APM_CalRGBDict_Gamma>(obj, "Gamma", IndirectRequirement.Either);
        if (val == null) { return; }
        // no special cases
        // no value restrictions
        ctx.Run<APM_GammaArray, PdfArray>(stack, val, obj);
        
    }


}

/// <summary>
/// CalRGBDict_Matrix 
/// </summary>
internal partial class APM_CalRGBDict_Matrix : APM_CalRGBDict_Matrix__Base
{
}


internal partial class APM_CalRGBDict_Matrix__Base : ISpecification<PdfDictionary>
{
    public static string Name { get; } = "CalRGBDict_Matrix";
    public static bool RuleGroup() { return false; }
    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) { return false; } // not used for children
    public static bool AppliesTo(decimal version, List<string> extensions) { return version >= 1.1m; }
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        var val = ctx.GetOptional<PdfArray, APM_CalRGBDict_Matrix>(obj, "Matrix", IndirectRequirement.Either);
        if (val == null) { return; }
        // no special cases
        // no value restrictions
        ctx.Run<APM_ArrayOf_9Numbers, PdfArray>(stack, val, obj);
        
    }


}

