// AUTOGENERATED DO NOT MODIFY

using PdfLexer;
using static PdfLexer.Validation.MathUtil;

namespace PdfLexer.Validation;

using System.Linq;

internal partial class APM_DestDict : APM_DestDict__Base
{
}

internal partial class APM_DestDict__Base : ISpecification<PdfDictionary>
{
    public static bool RuleGroup() { return true; }
    public static string Name { get; } = "DestDict";
    public static bool AppliesTo(decimal version, List<string> extensions) => true; // managed by links
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        ctx.Run<APM_DestDict_D, PdfDictionary>(stack, obj, parent);
        ctx.Run<APM_DestDict_SD, PdfDictionary>(stack, obj, parent);
        switch (ctx.Version) {
            case 1.1m:
            case 1.2m:
            case 1.3m:
            case 1.4m:
            case 1.5m:
            case 1.6m:
            case 1.7m:
            case 1.8m:
            case 1.9m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_11_12_13_14_15_16_17_18_19.Contains(x)))
                {
                    ctx.Fail<APM_DestDict>($"Unknown field {extra} for version {ctx.Version}");
                }
                break;
            case 2.0m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_20.Contains(x)))
                {
                    ctx.Fail<APM_DestDict>($"Unknown field {extra} for version {ctx.Version}");
                }
                break;
            default:
                break;
        }
    }

    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) 
    {
        return false;
    }

    public static List<string> AllowedFields_11_12_13_14_15_16_17_18_19 { get; } = new List<string> 
    {
        "D"
    };
    public static List<string> AllowedFields_20 { get; } = new List<string> 
    {
        "D", "SD"
    };
    


}

/// <summary>
/// DestDict_D Clause 12.3.2.4
/// </summary>
internal partial class APM_DestDict_D : APM_DestDict_D__Base
{
}


internal partial class APM_DestDict_D__Base : ISpecification<PdfDictionary>
{
    public static string Name { get; } = "DestDict_D";
    public static bool RuleGroup() { return false; }
    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) { return false; } // not used for children
    public static bool AppliesTo(decimal version, List<string> extensions) { return version >= 1.1m; }
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        var (val, wasIR) = ctx.GetRequired<PdfArray, APM_DestDict_D>(obj, "D", IndirectRequirement.Either);
        if (val == null) { return; }
        // no special cases
        // no value restrictions
        if (APM_DestXYZArray.MatchesType(ctx, val)) 
        {
            ctx.Run<APM_DestXYZArray, PdfArray>(stack, val, obj);
        } else if (APM_Dest0Array.MatchesType(ctx, val)) 
        {
            ctx.Run<APM_Dest0Array, PdfArray>(stack, val, obj);
        } else if (APM_Dest1Array.MatchesType(ctx, val)) 
        {
            ctx.Run<APM_Dest1Array, PdfArray>(stack, val, obj);
        } else if (APM_Dest4Array.MatchesType(ctx, val)) 
        {
            ctx.Run<APM_Dest4Array, PdfArray>(stack, val, obj);
        }else 
        {
            ctx.Fail<APM_DestDict_D>("D did not match any allowable types: '[DestXYZArray,Dest0Array,Dest1Array,Dest4Array]'");
        }
        
    }


}

/// <summary>
/// DestDict_SD 
/// </summary>
internal partial class APM_DestDict_SD : APM_DestDict_SD__Base
{
}


internal partial class APM_DestDict_SD__Base : ISpecification<PdfDictionary>
{
    public static string Name { get; } = "DestDict_SD";
    public static bool RuleGroup() { return false; }
    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) { return false; } // not used for children
    public static bool AppliesTo(decimal version, List<string> extensions) { return version >= 2.0m; }
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        var (val, wasIR) = ctx.GetOptional<PdfArray, APM_DestDict_SD>(obj, "SD", IndirectRequirement.Either);
        if (val == null) { return; }
        // no special cases
        // no value restrictions
        if (APM_DestXYZStructArray.MatchesType(ctx, val)) 
        {
            ctx.Run<APM_DestXYZStructArray, PdfArray>(stack, val, obj);
        } else if (APM_Dest0StructArray.MatchesType(ctx, val)) 
        {
            ctx.Run<APM_Dest0StructArray, PdfArray>(stack, val, obj);
        } else if (APM_Dest1StructArray.MatchesType(ctx, val)) 
        {
            ctx.Run<APM_Dest1StructArray, PdfArray>(stack, val, obj);
        } else if (APM_Dest4StructArray.MatchesType(ctx, val)) 
        {
            ctx.Run<APM_Dest4StructArray, PdfArray>(stack, val, obj);
        }else 
        {
            ctx.Fail<APM_DestDict_SD>("SD did not match any allowable types: '[DestXYZStructArray,Dest0StructArray,Dest1StructArray,Dest4StructArray]'");
        }
        
    }


}

