// AUTOGENERATED DO NOT MODIFY

using PdfLexer;
using static PdfLexer.Validation.MathUtil;

namespace PdfLexer.Validation;

using System.Linq;

internal partial class APM_MicrosoftWindowsLaunchParam : APM_MicrosoftWindowsLaunchParam__Base
{
}

internal partial class APM_MicrosoftWindowsLaunchParam__Base : ISpecification<PdfDictionary>
{
    public static bool RuleGroup() { return true; }
    public static string Name { get; } = "MicrosoftWindowsLaunchParam";
    public static bool AppliesTo(decimal version, List<string> extensions) => true; // managed by links
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        ctx.Run<APM_MicrosoftWindowsLaunchParam_F, PdfDictionary>(stack, obj, parent);
        ctx.Run<APM_MicrosoftWindowsLaunchParam_D, PdfDictionary>(stack, obj, parent);
        ctx.Run<APM_MicrosoftWindowsLaunchParam_O, PdfDictionary>(stack, obj, parent);
        ctx.Run<APM_MicrosoftWindowsLaunchParam_P, PdfDictionary>(stack, obj, parent);
        switch (ctx.Version) {
            case 1.1m:
            case 1.2m:
            case 1.3m:
            case 1.4m:
            case 1.5m:
            case 1.6m:
            case 1.7m:
            case 1.8m:
            case 1.9m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_11_12_13_14_15_16_17_18_19.Contains(x)))
                {
                    ctx.Fail<APM_MicrosoftWindowsLaunchParam>($"Unknown field {extra} for version {ctx.Version}");
                }
                break;
            default:
                break;
        }
    }

    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) 
    {
        return false;
    }

    public static List<string> AllowedFields_11_12_13_14_15_16_17_18_19 { get; } = new List<string> 
    {
        "D", "F", "O", "P"
    };
    


}

/// <summary>
/// MicrosoftWindowsLaunchParam_F Table 208
/// </summary>
internal partial class APM_MicrosoftWindowsLaunchParam_F : APM_MicrosoftWindowsLaunchParam_F__Base
{
}


internal partial class APM_MicrosoftWindowsLaunchParam_F__Base : ISpecification<PdfDictionary>
{
    public static string Name { get; } = "MicrosoftWindowsLaunchParam_F";
    public static bool RuleGroup() { return false; }
    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) { return false; } // not used for children
    public static bool AppliesTo(decimal version, List<string> extensions) { return version >= 1.1m && version < 2.0m; }
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        var (val, wasIR) = ctx.GetRequired<PdfString, APM_MicrosoftWindowsLaunchParam_F>(obj, "F", IndirectRequirement.Either);
        if (val == null) { return; }
        // no special cases
        // no value restrictions
        // no linked objects
        
    }


}

/// <summary>
/// MicrosoftWindowsLaunchParam_D 
/// </summary>
internal partial class APM_MicrosoftWindowsLaunchParam_D : APM_MicrosoftWindowsLaunchParam_D__Base
{
}


internal partial class APM_MicrosoftWindowsLaunchParam_D__Base : ISpecification<PdfDictionary>
{
    public static string Name { get; } = "MicrosoftWindowsLaunchParam_D";
    public static bool RuleGroup() { return false; }
    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) { return false; } // not used for children
    public static bool AppliesTo(decimal version, List<string> extensions) { return version >= 1.1m && version < 2.0m; }
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        var (val, wasIR) = ctx.GetOptional<PdfString, APM_MicrosoftWindowsLaunchParam_D>(obj, "D", IndirectRequirement.Either);
        if (val == null) { return; }
        // no special cases
        // no value restrictions
        // no linked objects
        
    }


}

/// <summary>
/// MicrosoftWindowsLaunchParam_O 
/// </summary>
internal partial class APM_MicrosoftWindowsLaunchParam_O : APM_MicrosoftWindowsLaunchParam_O__Base
{
}


internal partial class APM_MicrosoftWindowsLaunchParam_O__Base : ISpecification<PdfDictionary>
{
    public static string Name { get; } = "MicrosoftWindowsLaunchParam_O";
    public static bool RuleGroup() { return false; }
    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) { return false; } // not used for children
    public static bool AppliesTo(decimal version, List<string> extensions) { return version >= 1.1m && version < 2.0m; }
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        var (val, wasIR) = ctx.GetOptional<PdfString, APM_MicrosoftWindowsLaunchParam_O>(obj, "O", IndirectRequirement.Either);
        if (val == null) { return; }
        // no special cases
        
        
        if (!(val.Value == "open" || val.Value == "print")) 
        {
            ctx.Fail<APM_MicrosoftWindowsLaunchParam_O>($"Invalid value {val}, allowed are: ['open','print']");
        }
        // no linked objects
        
    }


}

/// <summary>
/// MicrosoftWindowsLaunchParam_P 
/// </summary>
internal partial class APM_MicrosoftWindowsLaunchParam_P : APM_MicrosoftWindowsLaunchParam_P__Base
{
}


internal partial class APM_MicrosoftWindowsLaunchParam_P__Base : ISpecification<PdfDictionary>
{
    public static string Name { get; } = "MicrosoftWindowsLaunchParam_P";
    public static bool RuleGroup() { return false; }
    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) { return false; } // not used for children
    public static bool AppliesTo(decimal version, List<string> extensions) { return version >= 1.1m && version < 2.0m; }
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        var (val, wasIR) = ctx.GetOptional<PdfString, APM_MicrosoftWindowsLaunchParam_P>(obj, "P", IndirectRequirement.Either);
        if (val == null) { return; }
        // no special cases
        // no value restrictions
        // no linked objects
        
    }


}

