// AUTOGENERATED DO NOT MODIFY

using PdfLexer;
using static PdfLexer.Validation.MathUtil;

namespace PdfLexer.Validation;

using System.Linq;

internal partial class APM_MicrosoftWindowsLaunchParam : APM_MicrosoftWindowsLaunchParam__Base
{
}

internal partial class APM_MicrosoftWindowsLaunchParam__Base : ISpecification<PdfDictionary>
{
    public static bool RuleGroup() { return true; }
    public static string Name { get; } = "MicrosoftWindowsLaunchParam";
    public static bool AppliesTo(decimal version, List<string> extensions) => true; // managed by links
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        ctx.Run<APM_MicrosoftWindowsLaunchParam_F, PdfDictionary>(stack, obj, parent);
        ctx.Run<APM_MicrosoftWindowsLaunchParam_D, PdfDictionary>(stack, obj, parent);
        ctx.Run<APM_MicrosoftWindowsLaunchParam_O, PdfDictionary>(stack, obj, parent);
        ctx.Run<APM_MicrosoftWindowsLaunchParam_P, PdfDictionary>(stack, obj, parent);
        switch (ctx.Version) {
            case 1.1m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_11.Contains(x)))
                {
                    ctx.Fail<APM_MicrosoftWindowsLaunchParam>($"Unknown field {extra} for version 1.1");
                }
                break;
            case 1.2m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_12.Contains(x)))
                {
                    ctx.Fail<APM_MicrosoftWindowsLaunchParam>($"Unknown field {extra} for version 1.2");
                }
                break;
            case 1.3m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_13.Contains(x)))
                {
                    ctx.Fail<APM_MicrosoftWindowsLaunchParam>($"Unknown field {extra} for version 1.3");
                }
                break;
            case 1.4m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_14.Contains(x)))
                {
                    ctx.Fail<APM_MicrosoftWindowsLaunchParam>($"Unknown field {extra} for version 1.4");
                }
                break;
            case 1.5m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_15.Contains(x)))
                {
                    ctx.Fail<APM_MicrosoftWindowsLaunchParam>($"Unknown field {extra} for version 1.5");
                }
                break;
            case 1.6m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_16.Contains(x)))
                {
                    ctx.Fail<APM_MicrosoftWindowsLaunchParam>($"Unknown field {extra} for version 1.6");
                }
                break;
            case 1.7m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_17.Contains(x)))
                {
                    ctx.Fail<APM_MicrosoftWindowsLaunchParam>($"Unknown field {extra} for version 1.7");
                }
                break;
            case 1.8m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_18.Contains(x)))
                {
                    ctx.Fail<APM_MicrosoftWindowsLaunchParam>($"Unknown field {extra} for version 1.8");
                }
                break;
            case 1.9m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_19.Contains(x)))
                {
                    ctx.Fail<APM_MicrosoftWindowsLaunchParam>($"Unknown field {extra} for version 1.9");
                }
                break;
            default:
                break;
        }
    }

    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) 
    {
        return false;
    }

    public static List<string> AllowedFields_11 { get; } = new List<string> 
    {
        "F", "D", "O", "P"
    };
    public static List<string> AllowedFields_12 { get; } = new List<string> 
    {
        "F", "D", "O", "P"
    };
    public static List<string> AllowedFields_13 { get; } = new List<string> 
    {
        "F", "D", "O", "P"
    };
    public static List<string> AllowedFields_14 { get; } = new List<string> 
    {
        "F", "D", "O", "P"
    };
    public static List<string> AllowedFields_15 { get; } = new List<string> 
    {
        "F", "D", "O", "P"
    };
    public static List<string> AllowedFields_16 { get; } = new List<string> 
    {
        "F", "D", "O", "P"
    };
    public static List<string> AllowedFields_17 { get; } = new List<string> 
    {
        "F", "D", "O", "P"
    };
    public static List<string> AllowedFields_18 { get; } = new List<string> 
    {
        "F", "D", "O", "P"
    };
    public static List<string> AllowedFields_19 { get; } = new List<string> 
    {
        "F", "D", "O", "P"
    };
    


}

/// <summary>
/// MicrosoftWindowsLaunchParam_F Table 208
/// </summary>
internal partial class APM_MicrosoftWindowsLaunchParam_F : APM_MicrosoftWindowsLaunchParam_F__Base
{
}


internal partial class APM_MicrosoftWindowsLaunchParam_F__Base : ISpecification<PdfDictionary>
{
    public static string Name { get; } = "MicrosoftWindowsLaunchParam_F";
    public static bool RuleGroup() { return false; }
    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) { return false; } // not used for children
    public static bool AppliesTo(decimal version, List<string> extensions) { return version >= 1.1m && version < 2.0m; }
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        var val = ctx.GetRequired<PdfString, APM_MicrosoftWindowsLaunchParam_F>(obj, "F", IndirectRequirement.Either);
        if (val == null) { return; }
        // no special cases
        // no value restrictions
        // no linked objects
        
    }


}

/// <summary>
/// MicrosoftWindowsLaunchParam_D 
/// </summary>
internal partial class APM_MicrosoftWindowsLaunchParam_D : APM_MicrosoftWindowsLaunchParam_D__Base
{
}


internal partial class APM_MicrosoftWindowsLaunchParam_D__Base : ISpecification<PdfDictionary>
{
    public static string Name { get; } = "MicrosoftWindowsLaunchParam_D";
    public static bool RuleGroup() { return false; }
    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) { return false; } // not used for children
    public static bool AppliesTo(decimal version, List<string> extensions) { return version >= 1.1m && version < 2.0m; }
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        var val = ctx.GetOptional<PdfString, APM_MicrosoftWindowsLaunchParam_D>(obj, "D", IndirectRequirement.Either);
        if (val == null) { return; }
        // no special cases
        // no value restrictions
        // no linked objects
        
    }


}

/// <summary>
/// MicrosoftWindowsLaunchParam_O 
/// </summary>
internal partial class APM_MicrosoftWindowsLaunchParam_O : APM_MicrosoftWindowsLaunchParam_O__Base
{
}


internal partial class APM_MicrosoftWindowsLaunchParam_O__Base : ISpecification<PdfDictionary>
{
    public static string Name { get; } = "MicrosoftWindowsLaunchParam_O";
    public static bool RuleGroup() { return false; }
    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) { return false; } // not used for children
    public static bool AppliesTo(decimal version, List<string> extensions) { return version >= 1.1m && version < 2.0m; }
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        var val = ctx.GetOptional<PdfString, APM_MicrosoftWindowsLaunchParam_O>(obj, "O", IndirectRequirement.Either);
        if (val == null) { return; }
        // no special cases
        // TODO value checks string-ascii
        // no linked objects
        
    }


}

/// <summary>
/// MicrosoftWindowsLaunchParam_P 
/// </summary>
internal partial class APM_MicrosoftWindowsLaunchParam_P : APM_MicrosoftWindowsLaunchParam_P__Base
{
}


internal partial class APM_MicrosoftWindowsLaunchParam_P__Base : ISpecification<PdfDictionary>
{
    public static string Name { get; } = "MicrosoftWindowsLaunchParam_P";
    public static bool RuleGroup() { return false; }
    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) { return false; } // not used for children
    public static bool AppliesTo(decimal version, List<string> extensions) { return version >= 1.1m && version < 2.0m; }
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        var val = ctx.GetOptional<PdfString, APM_MicrosoftWindowsLaunchParam_P>(obj, "P", IndirectRequirement.Either);
        if (val == null) { return; }
        // no special cases
        // no value restrictions
        // no linked objects
        
    }


}

