// AUTOGENERATED DO NOT MODIFY

using PdfLexer;
using static PdfLexer.Validation.MathUtil;

namespace PdfLexer.Validation;

using System.Linq;

internal partial class APM_OptContentProperties : APM_OptContentProperties__Base
{
}

internal partial class APM_OptContentProperties__Base : ISpecification<PdfDictionary>
{
    public static bool RuleGroup() { return true; }
    public static string Name { get; } = "OptContentProperties";
    public static bool AppliesTo(decimal version, List<string> extensions) => true; // managed by links
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        ctx.Run<APM_OptContentProperties_OCGs, PdfDictionary>(stack, obj, parent);
        ctx.Run<APM_OptContentProperties_D, PdfDictionary>(stack, obj, parent);
        ctx.Run<APM_OptContentProperties_Configs, PdfDictionary>(stack, obj, parent);
        switch (ctx.Version) {
            case 1.5m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_15.Contains(x)))
                {
                    ctx.Fail<APM_OptContentProperties>($"Unknown field {extra} for version 1.5");
                }
                break;
            case 1.6m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_16.Contains(x)))
                {
                    ctx.Fail<APM_OptContentProperties>($"Unknown field {extra} for version 1.6");
                }
                break;
            case 1.7m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_17.Contains(x)))
                {
                    ctx.Fail<APM_OptContentProperties>($"Unknown field {extra} for version 1.7");
                }
                break;
            case 1.8m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_18.Contains(x)))
                {
                    ctx.Fail<APM_OptContentProperties>($"Unknown field {extra} for version 1.8");
                }
                break;
            case 1.9m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_19.Contains(x)))
                {
                    ctx.Fail<APM_OptContentProperties>($"Unknown field {extra} for version 1.9");
                }
                break;
            case 2.0m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_20.Contains(x)))
                {
                    ctx.Fail<APM_OptContentProperties>($"Unknown field {extra} for version 2.0");
                }
                break;
            default:
                break;
        }
    }

    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) 
    {
        return false;
    }

    public static List<string> AllowedFields_15 { get; } = new List<string> 
    {
        "OCGs", "D", "Configs"
    };
    public static List<string> AllowedFields_16 { get; } = new List<string> 
    {
        "OCGs", "D", "Configs"
    };
    public static List<string> AllowedFields_17 { get; } = new List<string> 
    {
        "OCGs", "D", "Configs"
    };
    public static List<string> AllowedFields_18 { get; } = new List<string> 
    {
        "OCGs", "D", "Configs"
    };
    public static List<string> AllowedFields_19 { get; } = new List<string> 
    {
        "OCGs", "D", "Configs"
    };
    public static List<string> AllowedFields_20 { get; } = new List<string> 
    {
        "OCGs", "D", "Configs"
    };
    


}

/// <summary>
/// OptContentProperties_OCGs Table 98
/// </summary>
internal partial class APM_OptContentProperties_OCGs : APM_OptContentProperties_OCGs__Base
{
}


internal partial class APM_OptContentProperties_OCGs__Base : ISpecification<PdfDictionary>
{
    public static string Name { get; } = "OptContentProperties_OCGs";
    public static bool RuleGroup() { return false; }
    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) { return false; } // not used for children
    public static bool AppliesTo(decimal version, List<string> extensions) { return version >= 1.5m; }
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        var val = ctx.GetRequired<PdfArray, APM_OptContentProperties_OCGs>(obj, "OCGs", IndirectRequirement.Either);
        if (val == null) { return; }
        // no special cases
        // no value restrictions
        ctx.Run<APM_ArrayOfOCGindirect, PdfArray>(stack, val, obj);
        
    }


}

/// <summary>
/// OptContentProperties_D 
/// </summary>
internal partial class APM_OptContentProperties_D : APM_OptContentProperties_D__Base
{
}


internal partial class APM_OptContentProperties_D__Base : ISpecification<PdfDictionary>
{
    public static string Name { get; } = "OptContentProperties_D";
    public static bool RuleGroup() { return false; }
    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) { return false; } // not used for children
    public static bool AppliesTo(decimal version, List<string> extensions) { return version >= 1.5m; }
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        var val = ctx.GetRequired<PdfDictionary, APM_OptContentProperties_D>(obj, "D", IndirectRequirement.Either);
        if (val == null) { return; }
        // no special cases
        // no value restrictions
        ctx.Run<APM_OptContentConfig, PdfDictionary>(stack, val, obj);
        
    }


}

/// <summary>
/// OptContentProperties_Configs 
/// </summary>
internal partial class APM_OptContentProperties_Configs : APM_OptContentProperties_Configs__Base
{
}


internal partial class APM_OptContentProperties_Configs__Base : ISpecification<PdfDictionary>
{
    public static string Name { get; } = "OptContentProperties_Configs";
    public static bool RuleGroup() { return false; }
    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) { return false; } // not used for children
    public static bool AppliesTo(decimal version, List<string> extensions) { return version >= 1.5m; }
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        var val = ctx.GetOptional<PdfArray, APM_OptContentProperties_Configs>(obj, "Configs", IndirectRequirement.Either);
        if (val == null) { return; }
        // no special cases
        // no value restrictions
        ctx.Run<APM_ArrayOfOCConfig, PdfArray>(stack, val, obj);
        
    }


}

