// AUTOGENERATED DO NOT MODIFY

using PdfLexer;
using static PdfLexer.Validation.MathUtil;

namespace PdfLexer.Validation;

using System.Linq;

internal partial class APM_PointData : APM_PointData__Base
{
}

internal partial class APM_PointData__Base : ISpecification<PdfDictionary>
{
    public static bool RuleGroup() { return true; }
    public static string Name { get; } = "PointData";
    public static bool AppliesTo(decimal version, List<string> extensions) => true; // managed by links
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        ctx.Run<APM_PointData_Type, PdfDictionary>(stack, obj, parent);
        ctx.Run<APM_PointData_Subtype, PdfDictionary>(stack, obj, parent);
        ctx.Run<APM_PointData_Names, PdfDictionary>(stack, obj, parent);
        ctx.Run<APM_PointData_XPTS, PdfDictionary>(stack, obj, parent);
        switch (ctx.Version) {
            case 1.7m:
            case 1.8m:
            case 1.9m:
            case 2.0m:
                foreach (var extra in obj.Keys.Where(x=> !AllowedFields_17_18_19_20.Contains(x)))
                {
                    ctx.Fail<APM_PointData>($"Unknown field {extra} for version {ctx.Version}");
                }
                break;
            default:
                break;
        }
    }

    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) 
    {
        var c = ctx.Clone();
        c.Run<APM_PointData_Type, PdfDictionary>(new CallStack(), obj, null);
        c.Run<APM_PointData_Subtype, PdfDictionary>(new CallStack(), obj, null);
        if (c.Errors.Any())
        {
            return false;
        }
        return true;
    }

    public static List<string> AllowedFields_17_18_19_20 { get; } = new List<string> 
    {
        "Names", "Subtype", "Type", "XPTS"
    };
    


}

/// <summary>
/// PointData_Type Table 272
/// </summary>
internal partial class APM_PointData_Type : APM_PointData_Type__Base
{
}


internal partial class APM_PointData_Type__Base : ISpecification<PdfDictionary>
{
    public static string Name { get; } = "PointData_Type";
    public static bool RuleGroup() { return false; }
    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) { return false; } // not used for children
    public static bool AppliesTo(decimal version, List<string> extensions) { return false; }
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        var (val, wasIR) = ctx.GetRequired<PdfName, APM_PointData_Type>(obj, "Type", IndirectRequirement.Either);
        if (val == null) { return; }
        // no special cases
        
        
        if (!(val == PdfName.PtData)) 
        {
            ctx.Fail<APM_PointData_Type>($"Invalid value {val}, allowed are: [PtData]");
        }
        // no linked objects
        
    }


}

/// <summary>
/// PointData_Subtype 
/// </summary>
internal partial class APM_PointData_Subtype : APM_PointData_Subtype__Base
{
}


internal partial class APM_PointData_Subtype__Base : ISpecification<PdfDictionary>
{
    public static string Name { get; } = "PointData_Subtype";
    public static bool RuleGroup() { return false; }
    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) { return false; } // not used for children
    public static bool AppliesTo(decimal version, List<string> extensions) { return false; }
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        var (val, wasIR) = ctx.GetRequired<PdfName, APM_PointData_Subtype>(obj, "Subtype", IndirectRequirement.Either);
        if (val == null) { return; }
        // no special cases
        
        
        if (!(val == PdfName.Cloud)) 
        {
            ctx.Fail<APM_PointData_Subtype>($"Invalid value {val}, allowed are: [Cloud]");
        }
        // no linked objects
        
    }


}

/// <summary>
/// PointData_Names 
/// </summary>
internal partial class APM_PointData_Names : APM_PointData_Names__Base
{
}


internal partial class APM_PointData_Names__Base : ISpecification<PdfDictionary>
{
    public static string Name { get; } = "PointData_Names";
    public static bool RuleGroup() { return false; }
    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) { return false; } // not used for children
    public static bool AppliesTo(decimal version, List<string> extensions) { return false; }
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        var (val, wasIR) = ctx.GetRequired<PdfArray, APM_PointData_Names>(obj, "Names", IndirectRequirement.Either);
        if (val == null) { return; }
        // no special cases
        // no value restrictions
        ctx.Run<APM_ArrayOfNamesInPtData, PdfArray>(stack, val, obj);
        
    }


}

/// <summary>
/// PointData_XPTS 
/// </summary>
internal partial class APM_PointData_XPTS : APM_PointData_XPTS__Base
{
}


internal partial class APM_PointData_XPTS__Base : ISpecification<PdfDictionary>
{
    public static string Name { get; } = "PointData_XPTS";
    public static bool RuleGroup() { return false; }
    public static bool MatchesType(PdfValidator ctx, PdfDictionary obj) { return false; } // not used for children
    public static bool AppliesTo(decimal version, List<string> extensions) { return false; }
    public static void Validate(PdfValidator ctx, CallStack stack, PdfDictionary obj, IPdfObject? parent)
    {
        var (val, wasIR) = ctx.GetRequired<PdfArray, APM_PointData_XPTS>(obj, "XPTS", IndirectRequirement.Either);
        if (val == null) { return; }
        // no special cases
        // no value restrictions
        ctx.Run<APM_ArrayOfArraysXPTSValues, PdfArray>(stack, val, obj);
        
    }


}

