name: 'Create Release'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        default: '0.0.0'
      branch:
        description: 'Branch'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v3
    - name: tag
      shell: pwsh
      run: |
        $version = '${{ github.event.inputs.version }}';
        $branch = '${{ github.event.inputs.branch }}';
        git config user.email "pdflexer@github.com"
        git config user.name "pdflexer"
        git checkout -b $branch
        git tag -a "v$version" -m 'trigger github release'
        git push --tags
